---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ kdevops_extra_vars_yml }}"
      - "{{ kdevops_extra_vars_yaml }}"
      - "{{ kdevops_extra_vars_json }}"
      skip: true
  tags: vars

- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: linux

- name: Install NVMe tools
  become: yes
  become_method: sudo
  apt:
    name:
      - nvme-cli

- name: Install fstests build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - bison
      - flex
      - git
      - automake
      - gcc
      - libuuid1
      - quota
      - make
      - xfsprogs
      - e2fsprogs
      - btrfs-progs
      - gawk
      - uuid-runtime
      - acl
      - bc
      - dump
      - indent
      - libtool
      - lvm2
      - psmisc
      - sed
      - libacl1
      - libacl1-dev
      - "{{ pkg_libaio }}"
      - libaio-dev
      - uuid-dev
      - uuid-runtime
      - attr
      - libattr1
      - libattr1-dev
      - gdbm-l10n
      - libgdbm-dev
      - libssl-dev
      - xfslibs-dev
      - fio
      - libcap2-bin
      - libtool
      - gettext
      - ncurses-dev
      - parted
      - nfs-common
      - xfsdump
      - cifs-utils
    state: present
    update_cache: yes
  tags: [ 'fstests', 'deps' ]

- name: Install dependencies for building xfsprogs
  become: yes
  become_method: sudo
  apt:
    name:
      - libinih-dev
      - liburcu-dev
      - libicu-dev
      - libedit-dev
      - liblvm2-dev
      - libdevmapper-dev
      - libselinux1-dev
      - libsepol-dev
      - libpcre2-dev
      - pkg-config
      - libblkid-dev
  when: 'fstests_xfs_build_custom_xfsprogs|bool'
