---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ kdevops_extra_vars_yml }}"
      - "{{ kdevops_extra_vars_yaml }}"
      - "{{ kdevops_extra_vars_json }}"
      skip: true
  tags: vars

# Distro specific
- name: Install kdevops deps to run make menuconfig
  include_tasks: install-deps/main.yml
  when:
    - kdevops_first_run
