---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: deps

- name: Install sysbench deps
  become: yes
  become_method: sudo
  apt:
    name:
      - docker.io
      - locales
      - rsync
    state: present
    update_cache: yes
  tags: [ 'deps' ]
  when: 'sysbench_type_mysql_docker|bool'

- name: Install PosgreSQL build deps
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name:
      - bison
      - build-essential
      - flex
      - git
      - libicu-dev
      - libreadline-dev
      - pkgconf
      - sysbench
      - zlib1g-dev
    state: present
    update_cache: yes
  tags: [ 'deps' ]
  when: 'sysbench_type_postgresql_native|bool'

# acl - Required for running Ansible with unpriviledge user (sysbench_postgresql_user)
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
- name: Install PosgreSQL runtime deps
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name:
      - acl
      - xfsprogs
      - nvme-cli
    state: present
    update_cache: yes
  tags: [ 'deps' ]
  when: 'sysbench_type_postgresql_native|bool'

- name: Install sysbench deps
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name:
      - locales
      - rsync
    state: present
    update_cache: yes
  tags: [ 'deps' ]
  when: 'sysbench_type_postgresql_native|bool'
