---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ kdevops_extra_vars_yml }}"
      - "{{ kdevops_extra_vars_yaml }}"
      - "{{ kdevops_extra_vars_json }}"
      skip: true
  tags: vars

- name: Install dependencies to build Linux on host
  tags: [ 'deps' ]
  run_once: true
  local_action: import_tasks install-deps/main.yml
  when:
    - bootlinux_9p|bool

