---
- name: Generate tmpfs benchmark scripts
  ansible.builtin.template:
    src: "test00.j2"
    dest: "/tmp/test00-{{ file }}.sh"
    mode: "0777"
  vars:
    mount: "{{ item.command[0].mount }}"
    file: "{{ item.command[1].file }}"
    nrfiles: "{{ fsbenchmarks_test00_nrfiles }}"
    filesize: "{{ fsbenchmarks_test00_filesize }}"
    numjobs: "{{ fsbenchmarks_test00_numjobs }}"
    mountsize: "{{ fsbenchmarks_test00_mountsize }}"
  loop: "{{ mount_command }}"

- name: Run tmpfs benchmark
  ansible.builtin.command: /tmp/benchmark-{{ file }}.sh
  vars:
    file: "{{ item.command[1].file }}"
  loop: "{{ mount_command }}"

- name: Register running kernel release
  ansible.builtin.command: uname --kernel-release
  register: uname

- name: Collect benchmark results
  ansible.builtin.fetch:
    src: /tmp/log-{{ uname.stdout }}-{{ file }}
    dest: ../results/
    flat: yes
    validate_checksum: yes
  vars:
    file: "{{ item.command[1].file }}"
  loop: "{{ mount_command }}"
