---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ kdevops_extra_vars_yml }}"
      - "{{ kdevops_extra_vars_yaml }}"
      - "{{ kdevops_extra_vars_json }}"
      skip: true
  tags: vars

# Distro specific
- name: Install terraform
  include_tasks: install-deps/main.yml
